# Stage 1: Build the Angular application
FROM node:18 AS build-stage

# Set working directory to the monorepo root
WORKDIR /app

# Copy package.json and package-lock.json to the containers
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --force

# Copy the entire monorepo source code
COPY . .

RUN npm install -g @angular/cli@18

# Build the shared library first
RUN npm run build -- --project=shared --configuration production

# Build the specific microfrontend (mfe1)
RUN npm run build -- --project=mfe1 --configuration production

# Stage 2: Serve the application using Nginx
FROM nginx:alpine AS production-stage

COPY ./projects/mfe1/nginx.conf /etc/nginx/conf.d/default.conf


# Copy the built mfe1 microfrontend from the browser folder to the Nginx HTML directory
COPY --from=build-stage /app/dist/mfe1/browser/. /usr/share/nginx/html


# Expose the port for this microfrontend (e.g., 4201 for mfe1)
EXPOSE 5000

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]