# Stage 1: Build the Angular application
FROM node:18 AS build-stage

# Set working directory to the monorepo root
WORKDIR /app

# Copy package.json and package-lock.json to the containers
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --force

# Copy the entire monorepo source code
COPY . .

RUN npm install -g @angular/cli@18

# Build the shared library first
RUN npm run build -- --project=shared --configuration production

# Build the specific microfrontend (shell1)
RUN npm run build -- --project=shell1 --configuration production

# Stage 2: Serve the application using Nginx
FROM nginx:alpine AS production-stage

# COPY ./projects/shell1/nginx.conf /etc/nginx/conf.d/default.con


# Copy the built shell1 microfrontend from the browser folder to the Nginx HTML directory
COPY --from=build-stage /app/dist/shell1/browser/. /usr/share/nginx/html


# Expose the port for this microfrontend (e.g., 4201 for shell1)
EXPOSE 4200

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]