# Stage 1: Build the Angular application
FROM node:18 AS build-stage

# Set working directory to the monorepo root
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --force

# Copy the entire monorepo source code
COPY . .

RUN npm install -g @angular/cli@18

# Build the specific microfrontend (shell)
RUN npm run build -- --project=shell --outputPath=dist/shell --configuration production

# Stage 2: Serve the application using Nginx
FROM nginx:alpine AS production-stage

COPY ./projects/shell/nginx.conf /etc/nginx/conf.d/default.conf


# Copy the built shell microfrontend to the Nginx HTML directory
COPY --from=build-stage /app/dist/shell /usr/share/nginx/html

# Expose the port for this microfrontend (e.g., 4201 for shell)
EXPOSE 4200

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]